# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestM():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testM(self):
        self.driver.get("https://www.seleniumeasy.com/test/")
        self.driver.set_window_size(1616, 876)
        #element = self.driver.find_element(By.LINK_TEXT, "Alerts & Modals")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "Input Forms").click()
        self.driver.find_element(By.LINK_TEXT, "Input Form Submit").click()
        self.driver.find_element(By.NAME, "first_name").click()
        self.driver.find_element(By.NAME, "first_name").send_keys("George")
        self.driver.find_element(By.NAME, "last_name").send_keys("Bamidele")
        self.driver.find_element(By.NAME, "email").send_keys("deledpe@gmail.com")
        self.driver.find_element(By.NAME, "phone").send_keys("07476354756")
        self.driver.find_element(By.NAME, "address").send_keys("20 Milton Court, Wellesley road")
        self.driver.find_element(By.NAME, "city").send_keys("Twickenham")
        self.driver.find_element(By.NAME, "zip").send_keys("TW25SB")
        self.driver.find_element(By.CSS_SELECTOR, ".text-center > .row").click()
        self.driver.find_element(By.NAME, "state").click()
        dropdown = self.driver.find_element(By.NAME, "state")
        dropdown.find_element(By.XPATH, "//option[. = 'Arkansas']").click()
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "hosting").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

